import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { saira } from "./fonts";
import Providers from "../components/organisms/providers/query";
import { Suspense } from "react";
import SyncUserToken from "../components/organisms/layouts/SyncUserToken";
import I18nProvider from "../components/organisms/providers/I18nProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${saira.className} antialiased`}
      >
        <I18nProvider>
          <Providers>
            <SyncUserToken />
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </Providers>
        </I18nProvider>
      </body>
    </html>
  );
}
